### ISSUE TITLE
Adaptive detail level

### ISSUE THREAD

**Issue by timdiller** [kuromusha/mandelbrot-chaco#2]
As you zoom in farther and farther, you start to lose resolution on the edge of the stable region.  This can be fixed by increasing the value of `n` passed to `generate_mandelbrot`.
Here's what it looks like with the default `n=100`.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/852629/234382338-45f5edc9-27f8-4b1c-898c-7b1c136d5d58.png">
And here's a similar view with `n=1000`, but of course, this is much slower.
<img width="512" alt="Screenshot 2023-04-25 at 14 31 01" src="https://user-images.githubusercontent.com/852629/234383187-6fbdb02d-6d0f-4deb-8084-fa71d984bc17.png">
With a bit of experimentation, you should be able to determine a logarithmic relationship between the visible scale and the number of iterations.  For reference, in the initial view the vertical range is 3, and n=100 is sufficient;  in my example, when the vertical range is about 0.003, n=1000 seems to be more than sufficient.

**Comment by kuromusha** [comment]
@timdiller 
Thank you for your comment. I modified the code to change the number of iterations by the range by #4.
